### ISSUE TITLE
게시판 좋아요 기능 구현

### ISSUE THREAD

**Issue by chooh1010** [codingBottle/Helfy-SERVER#36]
## :bulb: 작업 내용
* 게시판의 좋아요 기능을 구현한다.
* HTTP 메소드 중 PUT을 활용하여 게시물에 좋아요를 업데이트한다.
* 좋아요를 추가하면 Post의 likeCount가 +1되고 삭제하면 -1된다. 이때 likeStatus도 바뀐다.
* Post를 조회할 때 likeStatus도 같이 조회된다.

## :white_check_mark: 상세 내용
- [ ] Likes 엔티티 구현
- [ ] Likes서비스 구현

**Comment by qwe916** [comment]
- redis를 이용해서 user와 likeStatus 관계를 저장하면 효율적일 것 같네요!
- Post에는 like 갯수만 저장하면 될 것 같네요
